const coinNames: Record<string, string> = {
  // Major L1s
  BTC: "Bitcoin",
  ETH: "Ethereum",
  SOL: "Solana",
  AVAX: "Avalanche",
  ADA: "Cardano",
  DOT: "Polkadot",
  ATOM: "Cosmos",
  NEAR: "NEAR Protocol",
  APT: "Aptos",
  SUI: "Sui",
  SEI: "Sei",
  INJ: "Injective",
  TON: "Toncoin",
  TRX: "TRON",
  BNB: "BNB Chain",
  XRP: "XRP",
  ICP: "Internet Computer",
  HBAR: "Hedera",
  ALGO: "Algorand",
  FTM: "Fantom",
  CELO: "Celo",
  CFX: "Conflux",
  NEO: "Neo",
  EOS: "EOS",
  XLM: "Stellar",
  ETC: "Ethereum Classic",
  BCH: "Bitcoin Cash",
  BSV: "Bitcoin SV",
  LTC: "Litecoin",
  DASH: "Dash",
  ZEC: "Zcash",
  XMR: "Monero",
  IOTA: "IOTA",
  MINA: "Mina",
  KAS: "Kaspa",
  S: "Sonic",
  BERA: "Berachain",
  MON: "Monad",
  HYPER: "HyperEVM",

  // L2s & Scaling
  ARB: "Arbitrum",
  OP: "Optimism",
  MATIC: "Polygon",
  POL: "Polygon",
  STRK: "Starknet",
  ZK: "ZKsync",
  BLAST: "Blast",
  MNT: "Mantle",
  MANTA: "Manta Network",
  LINEA: "Linea",
  ZETA: "ZetaChain",
  SCR: "Scroll",
  AZTEC: "Aztec",
  HEMI: "Hemi",
  ARK: "Ark",

  // DeFi
  AAVE: "Aave",
  MKR: "Maker",
  LDO: "Lido DAO",
  CRV: "Curve",
  SNX: "Synthetix",
  COMP: "Compound",
  SUSHI: "Sushi",
  UNI: "Uniswap",
  DYDX: "dYdX",
  GMX: "GMX",
  PENDLE: "Pendle",
  ENA: "Ethena",
  ONDO: "Ondo",
  ETHFI: "Ether.fi",
  MORPHO: "Morpho",
  SYRUP: "Maple Syrup",
  RESOLV: "Resolv",
  STABLE: "Stable",
  STBL: "Stbl",
  CAKE: "PancakeSwap",
  "1INCH": "1inch",
  RUNE: "THORChain",
  APEX: "ApeX Protocol",
  GNS: "Gains Network",
  RDNT: "Radiant Capital",
  PERP: "Perpetual Protocol",
  MAV: "Maverick",
  SKY: "Sky",
  USTC: "TerraClassicUSD",
  WLFI: "World Liberty Financial",
  VVV: "Venice",

  // Infrastructure & Data
  LINK: "Chainlink",
  FIL: "Filecoin",
  FET: "Fetch.AI",
  RNDR: "Render",
  RENDER: "Render",
  GRT: "The Graph",
  AR: "Arweave",
  PYTH: "Pyth Network",
  STX: "Stacks",
  TAO: "Bittensor",
  IO: "io.net",
  STORJ: "Storj",
  LIT: "Lit Protocol",
  BAND: "Band Protocol",
  API3: "API3",
  TRB: "Tellor",
  UMA: "UMA",

  // Gaming & Metaverse
  SAND: "The Sandbox",
  MANA: "Decentraland",
  AXS: "Axie Infinity",
  GALA: "Gala",
  IMX: "Immutable X",
  BIGTIME: "Big Time",
  YGG: "Yield Guild Games",
  PIXEL: "Pixels",
  MAVIA: "Heroes of Mavia",
  NXPC: "MapleStory Universe",
  SUPER: "SuperVerse",
  XAI: "Xai",

  // AI & DePIN
  AIXBT: "aixbt",
  GRIFFAIN: "Griffain",
  SOPH: "Sophon",

  // Memecoins
  DOGE: "Dogecoin",
  PEPE: "Pepe",
  SHIB: "Shiba Inu",
  FLOKI: "Floki",
  BONK: "Bonk",
  WIF: "dogwifhat",
  POPCAT: "Popcat",
  BRETT: "Brett",
  TURBO: "Turbo",
  MEW: "cat in a dogs world",
  GOAT: "Goatseus Maximus",
  FARTCOIN: "Fartcoin",
  MOODENG: "Moo Deng",
  PNUT: "Peanut the Squirrel",
  CHILLGUY: "Just a Chill Guy",
  DOOD: "Doodles",
  SPX: "SPX6900",
  BOME: "Book of Meme",
  VINE: "Vine",
  ZEREBRO: "Zerebro",
  HMSTR: "Hamster Kombat",
  TRUMP: "Official Trump",
  MELANIA: "Melania Meme",
  YZY: "Yeezy",
  PURR: "Purr",

  // Identity & Social
  ENS: "ENS",
  WLD: "Worldcoin",
  MASK: "Mask Network",
  ID: "SPACE ID",
  CYBER: "CyberConnect",
  ARKM: "Arkham",
  KAITO: "Kaito",
  SIGN: "Sign",

  // Ecosystem tokens
  TIA: "Celestia",
  JUP: "Jupiter",
  JTO: "Jito",
  W: "Wormhole",
  OSMO: "Osmosis",
  NTRN: "Neutron",
  DYM: "Dymension",
  PORTAL: "Portal",
  AEVO: "Aevo",
  NOT: "Notcoin",
  BLUR: "Blur",
  ZRO: "LayerZero",
  EIGEN: "EigenLayer",
  GRASS: "Grass",
  ME: "Magic Eden",
  MOVE: "Movement",
  VIRTUAL: "Virtuals Protocol",
  AI16Z: "ai16z",
  ANIME: "Animecoin",
  LAYER: "Solayer",
  IP: "Story Protocol",
  FORM: "Form",
  NIL: "=nil;",
  PARTI: "Particle Network",
  GPS: "GoPlus Security",
  PUMP: "PumpBTC",
  MERL: "Merlin Chain",
  TNSR: "Tensor",
  SAGA: "Saga",
  KMNO: "Kamino",
  REZ: "Renzo",
  ORDI: "Ordinals",
  ACE: "Fusionist",
  ALT: "AltLayer",
  PENGU: "Pudgy Penguins",
  TST: "TST",
  B: "B Protocol",
  INIT: "Initia",
  BABY: "Babylon",
  PROMPT: "Wayfinder",
  WCT: "WalletConnect",
  PROVE: "Prove",
  XPL: "XPL",
  ZORA: "Zora",
  FOGO: "Fogo",
  ASTER: "Aster",
  MEGA: "MegaETH",
  SKR: "Sukuri",
  "0G": "0G",
  "2Z": "2Z",
  CC: "CC",
  MET: "Metis",
  AVNT: "Avant",
  BIO: "BioProtocol",
  AERO: "Aerodrome",
  USUAL: "Usual",
  HYPE: "Hyperliquid",

  // Legacy / other
  APE: "ApeCoin",
  FTT: "FTX Token",
  KAVA: "Kava",
  THETA: "Theta",
  FLOW: "Flow",
  EGLD: "MultiversX",
  VET: "VeChain",
  XTZ: "Tezos",
  ZIL: "Zilliqa",
  ENJ: "Enjin",
  BAT: "Basic Attention Token",
  WAVES: "Waves",
  QTUM: "Qtum",
  ONT: "Ontology",
  ICX: "ICON",
  SC: "Siacoin",
  DCR: "Decred",
  ZEN: "Horizen",
  KDA: "Kadena",
  ACH: "Alchemy Pay",
  RSR: "Reserve Rights",
  RLC: "iExec",
  OCEAN: "Ocean Protocol",
  LRC: "Loopring",
  CELR: "Celer",
  CTSI: "Cartesi",
  SYN: "Synapse",
  MAGIC: "Magic",
  VELO: "Velo",
  HOOK: "Hooked Protocol",
  EDU: "Open Campus",
  LISTA: "Lista DAO",
  BB: "BounceBit",
  BANANA: "Banana Gun",
  DOGS: "DOGS",
  MEME: "Memecoin",
  GMT: "GMT",
  GAS: "Gas",
  PEOPLE: "ConstitutionDAO",
  PAXG: "PAX Gold",
  POLYX: "Polymesh",

  // kilo-denominated tokens
  kPEPE: "Pepe (1k)",
  kSHIB: "Shiba Inu (1k)",
  kBONK: "Bonk (1k)",
  kFLOKI: "Floki (1k)",
  kLUNC: "Terra Luna Classic (1k)",
  kNEIRO: "Neiro (1k)",
};

export function getCoinName(symbol: string): string | undefined {
  return coinNames[symbol] ?? coinNames[symbol.toUpperCase()];
}
